// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdRvYT7oo529mJW0y2NzOrjhtXV9uES4E',
    appId: '1:55482479939:web:8677b8dcf802b6ad936bf6',
    messagingSenderId: '55482479939',
    projectId: 'hungerzero-17',
    authDomain: 'hungerzero-17.firebaseapp.com',
    storageBucket: 'hungerzero-17.firebasestorage.app',
    measurementId: 'G-L2N4ES8CDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLlqqEHbRtnRnRxVqhz_rYDbsz42oHpg',
    appId: '1:55482479939:android:d2abd9eb89e9d039936bf6',
    messagingSenderId: '55482479939',
    projectId: 'hungerzero-17',
    storageBucket: 'hungerzero-17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4we47L7yMech6ERbd7B1cf_H8f6s4ag',
    appId: '1:55482479939:ios:07afa5c0557aee1d936bf6',
    messagingSenderId: '55482479939',
    projectId: 'hungerzero-17',
    storageBucket: 'hungerzero-17.firebasestorage.app',
    iosBundleId: 'com.example.hungerzero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4we47L7yMech6ERbd7B1cf_H8f6s4ag',
    appId: '1:55482479939:ios:07afa5c0557aee1d936bf6',
    messagingSenderId: '55482479939',
    projectId: 'hungerzero-17',
    storageBucket: 'hungerzero-17.firebasestorage.app',
    iosBundleId: 'com.example.hungerzero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdRvYT7oo529mJW0y2NzOrjhtXV9uES4E',
    appId: '1:55482479939:web:4dc082c0bdaaa809936bf6',
    messagingSenderId: '55482479939',
    projectId: 'hungerzero-17',
    authDomain: 'hungerzero-17.firebaseapp.com',
    storageBucket: 'hungerzero-17.firebasestorage.app',
    measurementId: 'G-4FJ7CK96H9',
  );
}
